### ISSUE TITLE
Feature Request: Support HSV output

### ISSUE THREAD

**Issue by dieseltravis** [cheerlights/cheerlights-arduino-library#1]
This would be useful when using the Adafruit NeoPixel library for some easy color transitions.

Maybe something like this in CheerLights.h:
```
// Public
uint16_t currentColorHue();
uint8_t currentColorSaturation();
uint8_t currentColorValue();
// Private
uint16_t _colorHue;
uint8_t _colorSat;
uint8_t _colorVal; 
```

Then in CheerLights.cpp:
```
// in _fetchColor create separate struct (or modify RGB one):
  // Map the color name to a HSV value
  static const struct {
    const char* name;
    uint16_t hue;
    uint8_t sat;
    uint8_t val;
  } colorMapHSV[] = {
    {"red", 0, 255, 255},
    {"green", 21845, 255, 255},
    {"blue", 43690, 255, 255},
    {"cyan", 32767, 255, 255},
    {"white", 0, 0, 255},
    {"warmwhite", 7123, 23, 253},
    {"oldlace", 7123, 23, 253},
    {"magenta", 54612, 255, 255},
    {"yellow", 10922, 255, 255},
    {"orange", 6954, 255, 255},
    {"purple", 54612, 255, 128},
    {"pink", 63627, 63, 255},
    {"black", 0, 0, 0}
  };

  for (const auto& colorHSV : colorMapHSV) {
    if (strcasecmp(_colorName, colorHSV.name) == 0) {
      _colorHue = colorHSV.hue;
      _colorSat = colorHSV.sat;
      _colorVal = colorHSV.val;
      break;
    }
  }
```

For returning values:
```
uint16_t CheerLights::currentColorHue() {
  return _colorHue;
}

uint8_t CheerLights::currentColorSaturation() {
  return _colorSat;
}

uint8_t CheerLights::currentColorValue() {
  return _colorVal;
}
```

**Comment by nothans** [comment]
Thanks for the detailed enhancement request. I was able to implement it fairly quickly with Releaser v1.0.4 (https://github.com/cheerlights/cheerlights-arduino-library/releases/tag/1.0.4). I agree this will help out with the  Adafruit NeoPixel library. If you come up with any other ideas/feedback, please share.

We are active on Discord: https://cheerlights.com/discord

**Comment by nothans** [comment]
Thanks for the detailed enhancement request. I was able to implement it fairly quickly with Releaser v1.0.4 (https://github.com/cheerlights/cheerlights-arduino-library/releases/tag/1.0.4). I agree this will help out with the Adafruit NeoPixel library. If you come up with any other ideas/feedback, please share.

We are active on Discord: https://cheerlights.com/discord
